spring:
  application:
    name: demography-service
  profiles:
    active: ${DEMOGRAPHY_PROFILE}
  config:
    import: "configserver:${CONFIG_SERVER_URL}"

server:
  port: 9049

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka