services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=soa
      - POSTGRES_USER=soa
      - POSTGRES_PASSWORD=soa
    networks:
      soa:
        ipv4_address: 172.18.0.2

  demography-service:
    depends_on:
      - consul
      - db
    build: ./services/demography
    dns: 172.18.0.3
    networks:
      soa:
        ipv4_address: 172.18.0.5

  server:
    depends_on:
      - consul
      - db
    build: .
    container_name: wildfly-server
#    ports:
#      - "20000:8080"
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    environment:
      - SOA_DB=jdbc:postgresql://172.18.0.2:5432/soa
      - SOA_USER=soa
      - SOA_PASSWORD=soa
      - SOA_COLLECTION_URL=http://172.18.0.3:8080/collection/
    dns: 172.18.0.3
    networks:
      soa:
        ipv4_address: 172.18.0.4

  consul:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
      - CONSUL_LOCAL_CONFIG={"service":{"name":"wildfly","tags":["java-ee"],"address":"172.18.0.4","port":8080},"check":{"id":"tcp","name":"TCP check on port 65101","tcp":"172.18.0.4:65101","interval":"10s","timeout":"2s"}}
    command: ["agent", "-dev", "-dns-port=53", "-recursor=8.8.8.8", "-client=0.0.0.0"]
    networks:
      soa:
        ipv4_address: 172.18.0.3
    ports:
      - "8500:8500"

networks:
  soa:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
